[Feat] con.chat() 메서드 구현
Team-Macos/con.chat pull request #2
Opened 2024-06-19 18:51 UTC by moonstrnck

## 테스크 제목

[[T-03] con.chat() 구현 - 채팅 시작](https://www.notion.so/eunmi/T-03-con-chat-5a50787f365c4005aeb6864110675107?pvs=4)

<br>

## 설명

- con.chat이라는 메서드를 정의하여, console 창에서 채팅 기능을 활성화하고 안내 메시지를 출력 기능을 구현
- 채팅이 시작되었다는 메세지와 지원 환경과 환경을 선택하도록 유도하는 메세지를 console 창에 출력

<br>

## 주안점

- 채팅 기능 활성화 상태를 은닉화하기 위하여 Class의 private field를 사용

<br>

## 체크리스트

- [x] 가장 최신 브랜치를 pull 하였습니다.
- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 코드 컨벤션에 맞게 작성했습니다.
- [x] base 브랜치명을 확인하였습니다.

2024-06-19 19:08 UTC, eunmmm commented on .eslintrc.cjs
> +    ecmaVersion: 13,
프라이빗 필드 문법을 사용하기 위해 ecmaVersion을 12에서 13으로 바꾸셨군요! 최신 ECMAScript 기능을 사용할 수 있게 되어 좋습니다.

ESLint 설정 파일에서 ECMAScript 버전을 업데이트 하는 것은 비교적 간단한 작업인데요! 이렇게 되면 고려할 점이 새로운 버전을 지원할 때마다 설정을 수동으로 업데이트해야 한다는 것입니다.

[`bebel-eslint`](https://github.com/babel/babel-eslint)를 사용하는 방안도 좋을 것 같습니다!
vite는 babel을 사용하지 않더라도 최신 문법을 사용할 수 있지만, ESLint는 기본적으로 모든 최신 기능을 지원하지 않기 때문에 수동으로 업데이트 할 필요 없이 최신 ECMAScript 기능을 지원해주는 `bebel-eslint`를 쓰는 방법도 생각해보시면 좋을 것 같습니다.

2024-06-19 19:19 UTC, eunmmm commented on src/conchat.js
> +export default window.con;
vite 환경에서 프라이빗 필드 문법을 사용하기 위해 window.con을 사용하여 인스턴스를 내보신 것 같습니다. 이렇게 하면 전역 객체인 window에 할당하여 전역적으로 접근 할 수 있을 것 같습니다!

이렇게 되면 어디서든 con 인스턴스를 사용할 수 있을 것 같은데요. 이렇게 window 객체에 직접 할당하는 것은 네임스페이스를 오염시킬 수 있을 것 같습니다. 또 [ES 모듈 시스템](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/)을 사용하기 때문에 일관성을 위해 모듈 시스템을 통해 가져오는 것도 고려해보면 좋을 것 같습니다!

2024-06-19 19:26 UTC, eunmmm approved these changes
채팅 기능을 활성화하는 기능을 잘 구현해주셨습니다!
몇 가지 요청드린 수정사항에 대해 확인해보고 고려해주세요.
수고하셨습니다!

2024-06-20 04:56 UTC, JeongHeonK requested changes
확인했습니다!

2024-06-20 04:56 UTC, JeongHeonK commented on .prettierrc.json
> +  "trailingComma": "es5",
triilingComma 설정을 es5로 변경할 경우, 
객체 리터럴, 배열 리터럴, 함수 매개변수 목록의 마지막 요소 뒤에는 쉼표를 추가하지 않습니다.

그러나 airbnb 스타일 가이드에서는 가능한 모든 곳에 후행 쉼표 사용을 권장하고 코드의 일관성을 유지합니다.

현재 저희는 airbnb 스타일 가이드를 따르기에 "all" 설정으로 되돌려야 합니다.

참고: https://github.com/airbnb/javascript
7.15

2024-06-20 05:10 UTC, moonstrnck commented on .prettierrc.json
> +  "trailingComma": "es5",
확인했습니다! 
프로젝트 코드 컨벤션으로 airbnb 스타일 가이드를 따르기로 합의 했음에도, 
습관적으로 함수의 인자 마지막에 trailing comma를 사용하는 것이 어색하게 느껴져 
섣불리 패키지 설정을 변경했던 것 같습니다. 
[airbnb 가이드](https://github.com/airbnb/javascript?tab=readme-ov-file#functions--signature-invocation-indentation)에서는 여러개 항목을 여러 줄로 개행 처리하여 
함수의 인자로 전달한 경우 trailing comma를 적용하는 것을 확인했습니다.
이 부분 수정 반영하도록 하겠습니다.

2024-06-20 06:44 UTC, moonstrnck commented on .eslintrc.cjs
> +    ecmaVersion: 13,
babel-eslint에 대한 제안 잘 확인하였습니다. 
ESLint 설정 파일에서 ecmaVersion을 12에서 13으로 수정한 이유는 말씀하신대로 프라이빗 필드 문법을 사용하기 위함이 맞습니다. 

오히려 최근에는 [bable-eslint](https://www.npmjs.com/package/babel-eslint)는 더 이상 유지 관리가 되지 않으며,  [babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser)를 사용한다고 하네요.

저희 프로젝트에서 실험적인 최신 문법을 사용할 일이 아직은 없을 것이라고 판단됩니다. 혹시나 다시 한번 필요성이 제기되면 그때 다시 babel/eslint-parser 사용에 대해 고려해보는 것도 좋을 것 같습니다.

2024-06-20 06:47 UTC, moonstrnck commented on src/conchat.js
> +export default window.con;
피드백 감사합니다.
저희 프로젝트에서는 브라우저 콘솔창에서 con 인스턴스에 접근이 가능해야합니다. 따라서 불가피하게 전역 객체에 할당하게 되었습니다. 🤓

2024-06-20 06:47 UTC, JeongHeonK approved these changes

2024-06-20 07:02 UTC, merged